[workspace]

members = [
    "nativeshell_build",
    "nativeshell",
    "nativeshell_ng_test",
    "core/rust",
    "core/rust_derive",
]

exclude = [
    "build_test/project1",
    "build_test/project2",
]
