[package]
name = "nativeshell_derive"
version = "0.1.1"

[lib]
proc-macro = true

edition = "2018"

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-error = "1.0"
convert_case = "0.5.0"
nativeshell_core = { path = "../core" }